#!/bin/bash
SCRIPT_DIR=$(cd $(dirname $0);pwd)

# Directory to save output
OUTPUT_DIR="${SCRIPT_DIR}/tmp"
mkdir -p ${OUTPUT_DIR}

# Url
# Got by google chrome developer console on https://www.alexa.com/topsites
# var out = ""; $(".site-listing .DescriptionCell p a").each(function (i, a) { out += a.getAttribute("href").replace("/siteinfo/", "") + " " }); console.log(out)
NO_REPLY_WEBSITE=not-found-yay.jp
URLS="google.com youtube.com ${NO_REPLY_WEBSITE} facebook.com baidu.com wikipedia.org reddit.com yahoo.com google.co.in qq.com taobao.com amazon.com twitter.com tmall.com google.co.jp live.com instagram.com vk.com sohu.com sina.com.cn jd.com weibo.com 360.cn google.de google.co.uk google.com.br google.fr google.ru yandex.ru netflix.com linkedin.com twitch.tv google.it t.co google.com.hk google.es pornhub.com alipay.com xvideos.com yahoo.co.jp google.ca google.com.mx ebay.com microsoft.com bing.com ok.ru imgur.com office.com bongacams.com hao123.com aliexpress.com"

go run ${SCRIPT_DIR}/fetchall.go ${OUTPUT_DIR} ${URLS}

# ========== output
# url `google.com` has no prefix. addding prefix http://...
# url `youtube.com` has no prefix. addding prefix http://...
# url `not-found-yay.jp` has no prefix. addding prefix http://...
# url `facebook.com` has no prefix. addding prefix http://...
# url `baidu.com` has no prefix. addding prefix http://...
# url `wikipedia.org` has no prefix. addding prefix http://...
# url `reddit.com` has no prefix. addding prefix http://...
# url `yahoo.com` has no prefix. addding prefix http://...
# url `google.co.in` has no prefix. addding prefix http://...
# url `qq.com` has no prefix. addding prefix http://...
# url `taobao.com` has no prefix. addding prefix http://...
# url `amazon.com` has no prefix. addding prefix http://...
# url `twitter.com` has no prefix. addding prefix http://...
# url `tmall.com` has no prefix. addding prefix http://...
# url `google.co.jp` has no prefix. addding prefix http://...
# url `live.com` has no prefix. addding prefix http://...
# url `instagram.com` has no prefix. addding prefix http://...
# url `vk.com` has no prefix. addding prefix http://...
# url `sohu.com` has no prefix. addding prefix http://...
# url `sina.com.cn` has no prefix. addding prefix http://...
# url `jd.com` has no prefix. addding prefix http://...
# url `weibo.com` has no prefix. addding prefix http://...
# url `360.cn` has no prefix. addding prefix http://...
# url `google.de` has no prefix. addding prefix http://...
# url `google.co.uk` has no prefix. addding prefix http://...
# url `google.com.br` has no prefix. addding prefix http://...
# url `google.fr` has no prefix. addding prefix http://...
# url `google.ru` has no prefix. addding prefix http://...
# url `yandex.ru` has no prefix. addding prefix http://...
# url `netflix.com` has no prefix. addding prefix http://...
# url `linkedin.com` has no prefix. addding prefix http://...
# url `twitch.tv` has no prefix. addding prefix http://...
# url `google.it` has no prefix. addding prefix http://...
# url `t.co` has no prefix. addding prefix http://...
# url `google.com.hk` has no prefix. addding prefix http://...
# url `google.es` has no prefix. addding prefix http://...
# url `pornhub.com` has no prefix. addding prefix http://...
# url `alipay.com` has no prefix. addding prefix http://...
# url `xvideos.com` has no prefix. addding prefix http://...
# url `yahoo.co.jp` has no prefix. addding prefix http://...
# url `google.ca` has no prefix. addding prefix http://...
# url `google.com.mx` has no prefix. addding prefix http://...
# url `ebay.com` has no prefix. addding prefix http://...
# url `microsoft.com` has no prefix. addding prefix http://...
# url `bing.com` has no prefix. addding prefix http://...
# url `ok.ru` has no prefix. addding prefix http://...
# url `imgur.com` has no prefix. addding prefix http://...
# url `office.com` has no prefix. addding prefix http://...
# url `bongacams.com` has no prefix. addding prefix http://...
# url `hao123.com` has no prefix. addding prefix http://...
# url `aliexpress.com` has no prefix. addding prefix http://...
# Get http://not-found-yay.jp: dial tcp: lookup not-found-yay.jp: no such host
# 0.19s    3154 http://t.co
# 0.21s   12815 http://google.com
# 0.24s   12674 http://google.co.jp
# 0.26s   20047 http://yahoo.co.jp
# 0.26s    3574 http://live.com
# 0.29s  100460 http://bing.com
# 0.32s   14844 http://google.ru
# 0.32s   14338 http://google.com.hk
# 0.33s   14794 http://google.fr
# 0.33s   14851 http://google.com.mx
# 0.34s   14754 http://google.es
# 0.35s   14762 http://google.it
# 0.37s   14754 http://google.de
# 0.39s   14767 http://google.com.br
# 0.42s  133144 http://twitter.com
# 0.43s   14766 http://google.co.uk
# 0.45s      81 http://baidu.com
# 0.57s   14734 http://google.co.in
# 0.57s   14751 http://google.ca
# 0.58s   17265 http://twitch.tv
# 0.60s  366857 http://facebook.com
# 0.75s   61337 http://office.com
# 0.79s   43693 http://linkedin.com
# 0.84s  181044 http://reddit.com
# 0.94s  229495 http://tmall.com
# 0.94s  144309 http://ebay.com
# 0.95s  256512 http://qq.com
# 1.03s  604587 http://sina.com.cn
# 1.04s   60680 http://weibo.com
# 1.03s    1248 http://xvideos.com
# 1.05s  522201 http://hao123.com
# 1.09s  218298 http://sohu.com
# 1.19s  167331 http://jd.com
# 1.23s  145612 http://microsoft.com
# 1.27s   38399 http://aliexpress.com
# 1.34s  516324 http://yahoo.com
# 1.36s  247513 http://taobao.com
# 1.36s  134741 http://imgur.com
